E
======================================================================
ERROR: test_login (test.test_case.example_test_case.ExampleTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\py_workspace\PyAutomatedTesting\AutomatedTestingProject\test\test_case\example_test_case.py", line 23, in test_login
    example_page.login()
  File "D:\py_workspace\PyAutomatedTesting\AutomatedTestingProject\test\page\sub_pages\login_page.py", line 23, in login
    a.click()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: chrome=69.0.3497.81)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 6.1.7601 SP1 x86_64)


----------------------------------------------------------------------
Ran 1 test in 55.066s

FAILED (errors=1)
